# Generated by Django 4.0 on 2021-12-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_movie_language_remove_serie_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
