# Generated by Django 4.0 on 2021-12-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_image_movie_thumbnail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
