# Generated by Django 4.0 on 2021-12-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese')], default='pt-br', max_length=255),
            preserve_default=False,
        ),
    ]
