# Generated by Django 4.0 on 2021-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_movie_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='', upload_to='static/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='static/videos/'),
        ),
    ]
