# Generated by Django 4.0 on 2021-12-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_movie_poster_alter_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
    ]
