# Generated by Django 4.0 on 2021-12-28 16:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_movie_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=home.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, upload_to=home.models.get_file_path),
        ),
    ]
