# Generated by Django 4.0 on 2021-12-28 20:14

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_movie_poster_alter_movie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('poster', models.ImageField(upload_to=home.models.get_file_path)),
                ('lang', models.CharField(choices=[('en', 'Inglês'), ('pt-br', 'Português')], max_length=255)),
                ('video', models.FileField(blank=True, upload_to=home.models.get_file_path)),
            ],
        ),
    ]
