# Generated by Django 4.0 on 2021-12-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
