# Generated by Django 4.0 on 2021-12-29 22:21

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_series_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='season',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to=home.models.get_file_path),
        ),
    ]
