# Generated by Django 4.0 on 2021-12-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_serie_season_alter_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='video',
        ),
    ]
