# Generated by Django 4.0 on 2021-12-29 23:32

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_episode_serie_slug_alter_episode_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to=home.models.get_file_path),
        ),
    ]
