# Generated by Django 4.0 on 2021-12-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_episode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='season',
        ),
    ]
