# Generated by Django 4.0 on 2021-12-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_serie_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
