# Generated by Django 4.0 on 2021-12-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_serie_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='file',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='serie',
            name='season',
            field=models.IntegerField(default=1),
        ),
    ]
