# Generated by Django 4.0 on 2021-12-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_file_episode_video_alter_serie_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='title',
            new_name='serie_title',
        ),
    ]
